### ISSUE TITLE
Unauthorized access

### ISSUE THREAD

**Issue by Neoziox** [extras-evolution/evocheck#13]
After adding index.html everywhere, I have "unauthorized access" in the manager.
And I've had the bad idea to disconnect: unable to display the login page (unauthorized access too).

**Comment by Deesen** [comment]
This probably has to do with your server-settings. You can try to put this into your root .htaccess-file:

`DirectoryIndex index.php index.html`

https://stackoverflow.com/a/15992307

**Comment by Neoziox** [comment]
Exactly. Thanks a lot!
